export const APPLICANTS = [
  {
    "Full Name": "Percival Archer",
    "Hiring Stage": "Interview",
    "Applied Date": "13 July 2023",
    "Job Role": "Designer",
    Action: "See Application",
  },
  {
    "Full Name": "Eleanor Smith",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "15 July 2023",
    "Job Role": "UI/UX Designer",
    Action: "See Application",
  },
  {
    "Full Name": "Aiden Johnson",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "17 July 2023",
    "Job Role": "Front-end Developer",
    Action: "See Application",
  },
  {
    "Full Name": "Lily Brown",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "19 July 2023",
    "Job Role": "Project Manager",
    Action: "See Application",
  },
  {
    "Full Name": "Oliver White",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "21 July 2023",
    "Job Role": "Marketing Specialist",
    Action: "See Application",
  },
  {
    "Full Name": "Sophia Wilson",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "23 July 2023",
    "Job Role": "Software Engineer",
    Action: "See Application",
  },
  {
    "Full Name": "Noah Taylor",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "25 July 2023",
    "Job Role": "Data Analyst",
    Action: "See Application",
  },
  {
    "Full Name": "Isabella Lee",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "27 July 2023",
    "Job Role": "Product Manager",
    Action: "See Application",
  },
  {
    "Full Name": "Liam Hall",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "29 July 2023",
    "Job Role": "Graphic Designer",
    Action: "See Application",
  },
  {
    "Full Name": "Ava Clark",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "31 July 2023",
    "Job Role": "Content Writer",
    Action: "See Application",
  },
  {
    "Full Name": "Olivia Turner",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "2 August 2023",
    "Job Role": "Software Developer",
    Action: "See Application",
  },
  {
    "Full Name": "William Miller",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "4 August 2023",
    "Job Role": "Marketing Manager",
    Action: "See Application",
  },
  {
    "Full Name": "Emma Davis",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "6 August 2023",
    "Job Role": "Data Scientist",
    Action: "See Application",
  },
  {
    "Full Name": "James Wilson",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "8 August 2023",
    "Job Role": "Project Coordinator",
    Action: "See Application",
  },
  {
    "Full Name": "Charlotte Moore",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "10 August 2023",
    "Job Role": "UX Designer",
    Action: "See Application",
  },
  {
    "Full Name": "Mason Brown",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "12 August 2023",
    "Job Role": "Front-end Developer",
    Action: "See Application",
  },
  {
    "Full Name": "Amelia Smith",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "14 August 2023",
    "Job Role": "Content Writer",
    Action: "See Application",
  },
  {
    "Full Name": "Liam Johnson",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "16 August 2023",
    "Job Role": "Graphic Designer",
    Action: "See Application",
  },
  {
    "Full Name": "Evelyn Wilson",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "18 August 2023",
    "Job Role": "Software Engineer",
    Action: "See Application",
  },
  {
    "Full Name": "Noah Miller",
    "Hiring Stage": getRandomHiringStage(),
    "Applied Date": "20 August 2023",
    "Job Role": "Product Manager",
    Action: "See Application",
  },
];

function getRandomHiringStage() {
  const hiringStages = ["Interview", "Shortlisted", "Declined", "Hired"];
  return hiringStages[Math.floor(Math.random() * hiringStages.length)];
}
